### ISSUE TITLE
Example error: { statusCode: 401, data: '{"error": "invalid_grant"}' }

### ISSUE THREAD

**Issue by sabas1080** [shernshiou/node-uber#48] opened 2016-08-05 19:39 UTC
I have the next error, run example

`{ statusCode: 401, data: '{"error": "invalid_grant"}' }
`

Thanks

**Comment by harlev** [comment] 2016-09-06 02:40
I have a similar issue, listed also [here](http://stackoverflow.com/q/39339710/1363)

when I'm trying to login with my Uber developer credentials (same one I used to create the app on Uber), everything works perfectly, which leads me to believe the implementation makes at least basic sense.

The problem is when I try another, unrelated, Uber login. Then the error code coming back is invalid_grant

**Comment by agraebe** [comment] 2017-02-26 00:59
I believe this was due to the fact that this wrapper used the v1 auth endpoints. This should be fixed with #53. Let me know if you experience further issues (with reproduction steps and all details).

**Closed by agraebe** 2017-02-26 00:59 UTC

**Comment by GINGO2397** [comment] 2017-08-08 23:31
Hi, I continue with the error;
statusCode: 401, data: '{"error": "invalid_grant"}' }. 
I don´t understand quite well the fix 53. Thanks in advance for your help.
